services:
  db:
    image: mongo:7
    container_name: week1_db
    ports:
      - "27017:27017"

  api:
    build: ./api
    container_name: week1_api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://db:27017/week1
      JWT_SECRET: dev-secret
    depends_on:
      - db
